### ISSUE TITLE
Demo Link is broken

### ISSUE THREAD

**Issue by Shobhit1** [revanth0212/react-charges-table#6]
Link for Demo page is broken. gives 404.

**Comment by vivekparekh8** [comment]
+1

**Comment by revanthCopart** [comment]
Done. Some issue with `gh-pages`.

**Comment by Shobhit1** [comment]
Still broken! ;D

**Comment by vivekparekh8** [comment]
There is no index.html in `gh-pages` branch. `react-gh-pages` [steps](https://github.com/gitname/react-gh-pages/blob/master/README.md).

**Comment by revanth0212** [comment]
My bad. Made a mistake while changing build script. Accidentally changed deploy script. Should be working now.

**Comment by revanth0212** [comment]
![image](https://user-images.githubusercontent.com/35203638/44696396-05183680-aa3d-11e8-9424-856e4fcffc8f.png)

**Comment by revanth0212** [comment]
![image](https://user-images.githubusercontent.com/35203638/44696494-6b04be00-aa3d-11e8-935a-091314fde01b.png)
